apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: airquality-device
  name: airquality-device
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: airquality-device
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: airquality-device
    spec:
      containers:
        - env:
            - name: MQTT_BROKER
              value: mosquitto
            - name: MQTT_PORT
              value: "1883"
          image: ashwink07/airquality_device:v1.0.0 
          name: airquality-device
      restartPolicy: Always
