# Use the official Ubuntu image as base
FROM ubuntu:latest

# Install Mosquitto
RUN apt-get update && apt-get install -y mosquitto && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Expose Mosquitto default ports (1883 for MQTT, 8883 for MQTT over TLS)
EXPOSE 1883 8883

# Run Mosquitto broker
CMD ["/usr/sbin/mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
