apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: subscriber
  name: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subscriber
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: subscriber
    spec:
      containers:
        - env:
            - name: MQTT_BROKER
              value: mosquitto
            - name: MQTT_PORT
              value: "1883"
          image: ashwink07/serverless:v1.0.0
          name: subscriber
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
